/**
 * Instrument Core software for Modular Musical Instrument
 *
 * Copyright (C) 2016-2017 ECE 2017.011, University of Waterloo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef MIDI_INSTRS_H
#define MIDI_INSTRS_H

const char* midi_gm1_instr[] = {
	"AcstGrandPiano",
	"BrightAcstcPiano",
	"ElecGrandPiano",
	"HonkyTonkPiano",
	"ElecPiano1",
	"ElecPiano2",
	"Harpsichord",
	"Clavi",
	"Celesta",
	"Glockenspiel",
	"MusicBox",
	"Vibraphone",
	"Marimba",
	"Xylophone",
	"TubularBells",
	"Dulcimer",
	"DrawbarOrgan",
	"PercussiveOrgan",
	"RockOrgan",
	"ChurchOrgan",
	"ReedOrgan",
	"Accordion",
	"Harmonica",
	"TangoAccordion",
	"AcstGuitarNylon",
	"AcstGuitarSteel",
	"ElecGuitarJazz",
	"ElecGuitarClean",
	"ElecGuitarMuted",
	"OverdrivenGuitar",
	"DistortionGuitar",
	"GuitarHarmonics",
	"AcstBass",
	"ElecBassFinger",
	"ElecBassPick",
	"FretlessBass",
	"SlapBass1",
	"SlapBass2",
	"SynthBass1",
	"SynthBass2",
	"Violin",
	"Viola",
	"Cello",
	"Contrabass",
	"TremoloStrings",
	"PizzicatoStrings",
	"OrchestralHarp",
	"Timpani",
	"StringEnsemble1",
	"StringEnsemble2",
	"SynthStrings1",
	"SynthStrings2",
	"ChoirAahs",
	"VoiceOohs",
	"SynthVoice",
	"OrchestraHit",
	"Trumpet",
	"Trombone",
	"Tuba",
	"MutedTrumpet",
	"FrenchHorn",
	"BrassSection",
	"SynthBrass1",
	"SynthBrass2",
	"SopranoSax",
	"AltoSax",
	"TenorSax",
	"BaritoneSax",
	"Oboe",
	"EnglishHorn",
	"Bassoon",
	"Clarinet",
	"Piccolo",
	"Flute",
	"Recorder",
	"PanFlute",
	"BlownBottle",
	"Shakuhachi",
	"Whistle",
	"Ocarina",
	"Lead1Square",
	"Lead2Sawtooth",
	"Lead3Calliope",
	"Lead4Chiff",
	"Lead5Charang",
	"Lead6Voice",
	"Lead7fifths",
	"Lead8Bass+Lead",
	"Pad1NewAge",
	"Pad2Warm",
	"Pad3Polysynth",
	"Pad4Choir",
	"Pad5Bowed",
	"Pad6Metallic",
	"Pad7Halo",
	"Pad8Sweep",
	"FX1Rain",
	"FX2Soundtrack",
	"FX3Crystal",
	"FX4Atmosphere",
	"FX5Brightness",
	"FX6Goblins",
	"FX7Echoes",
	"FX8SciFi",
	"Sitar",
	"Banjo",
	"Shamisen",
	"Koto",
	"Kalimba",
	"Bagpipe",
	"Fiddle",
	"Shanai",
	"TinkleBell",
	"Agogo",
	"SteelDrums",
	"Woodblock",
	"TaikoDrum",
	"MelodicTom",
	"SynthDrum",
	"ReverseCymbal",
	"GuitarFretNoise",
	"BreathNoise",
	"Seashore",
	"BirdTweet",
	"TelephoneRing",
	"Helicopter",
	"Applause",
	"Gunshot",
};

#endif // MIDI_INSTRS_H
